var courses_data = [
	{
		"id": 0,
		"title": "Graduacja 2018",
		"description": "Zapraszamy na Spotkanie Graduacyjne – czyli uroczyste zakończenie studiów, a następnie Spotkanie Absolwentów, które odbędzie się 25 maja 2018r. o godz. 19:00 w Wyższej Szkole Zarządzania i Bankowości przy al. Kijowskiej 14. Szczegóły oraz informacja o zapisach znajduje się na stronie www.wszib.edu.pl/graduacja",
		"image": "images/0.jpg",
		"author": "Autor 1",
		"duration": "11.05.2018",
		"categories": ["#zakończenie", " #impreza"],
		"is_new": true,
	},
	{
		"id": 1,
		"title": "Kampania Rowerem do pracy",
		"description": "Zapraszamy do udziału w Kampanii pod hasłem: „Rowerem do pracy, czyli – dom, rower, praca… i tak w kółko” organizowanej przez Wydział Gospodarki Komunalnej Urzędu Miasta Krakowa. Kampania ma na celu zachęcenie pracowników do korzystania z roweru, jako środka transportu. Spróbujcie Państwo przejechać na rowerze do pracy kilka razy w tygodniu. W 2017 r. w projekcie wzięło udział 50 pracodawców z sektora prywatnego i publicznego, a w ciągu 5 pełnych miesięcy testowej kampanii rowerem podróżowało każdego miesiąca średnio ponad 350 osób pokonując w sumie blisko 51 500 km. WSZIB też miał w tym swój udział. ",
		"image": "images/1.jpg",
		"author": "Autor 2",
		"duration": "10.05.2018",
		"categories": ["#zdrowie", " #ruch"],
	},
	{
		"id": 2,
		"title": "Program Erasmus+ ",
		"description": "W dniach 23-27 kwietnia 2018r. pracownicy WSZiB brali udział w szkoleniach, warsztatach i spotkaniach ze studentami w ramach Programu Erasmus+ na University of Foggia we Włoszech. Od 14 lat uczestniczymy w programie Erasmus przyjmując także w nasze progi studentów z krajów UE. ",
		"image": "images/2.jpg",
		"author": "Autor 3",
		"duration": "08.05.2018",
		"categories": ["#erasmus", " #integracja"],
	},
	{
		"id": 3,
		"title": "Debata na temat polityki surowcowej",
		"description": "W Wyższej Szkole Zarządzania i Bankowości w Krakowie odbędzie się kolejna debata Fundacji oraz Polskiego Klubu Ekologicznego. Spotkanie odbędzie się 14.05.2018 r o godzinie 16:30  w sali 13 K przy al. Kijowskiej 14. Zapraszamy wszystkich zainteresowanych także ze względu na prelegentów, którzy zgłosili udział w naszym spotkaniu. Prof. dr hab. Mariusz Orion Jędrysik Sekretarz Stanu, Główny Geolog Kraju (Ministerstwo Środowiska) będzie mówił o polityce surowcowej Państwa, rozwoju zrównoważonym i barierach ekologicznych. Z kolei Joanna Trzaskowska oraz Marcin Bielewski z Departamentu Geologii i Koncesji Geologicznych Ministerstwa Środowiska zaprezentują nowelizacje prawa geologicznego i koncesje geologiczne. Zapraszamy do udziału w debacie i liczymy na Państwa udział.",
		"image": "images/2.jpg",
		"author": "Autor 1",
		"duration": "07.05.2018",
		"categories": ["#surowce", " #debata"]
	},
	{
		"id": 4,
		"title": "Paradoksy i ułomności strategii walki ze smogiem",
		"description": "Podczas kolejnej debaty organizowanej przez Polski Klub Ekologiczny i Fundację MIPiSE szukaliśmy odpowiedzi na pytania: Czy strategia walki ze smogiem jest skuteczna? Kto traci kto zyskuje? Czy nie należy poddać rewizji aktualną strategie? Spotkanie odbyło się 19.04.2018 r. w siedzibie Wyższej Szkoły Zarządzania i Bankowości w Krakowie. W debacie wzięli udział prelegenci: Marcin Popkiewicz - fizyk, autor książek m.in. „Rewolucja energetyczna ale po co?”, znany członkom PKE z poprzednich debat oraz dr Ludomir Duda - chemik, termodynamik, audytor energetyczny Marcin Orłowski- Firma Frapol Wrocław. Dziękujemy za udział w debacie.",
		"image": "images/4.jpg",
		"author": "Autor 2",
		"duration": "16.04.2018",
		"categories": ["#smog", " #zwalczanie"],
	},
	{
		"id": 5,
		"title": "Targi Edukacji i Pracy w WSZiB ",
		"description": "13 kwietnia 2018 r. odbyły się Targi Edukacji i Pracy organizowane wspólnie z Centrum Edukacji i Pracy Młodzieży Ochotniczych Hufców Pracy w Krakowie. Uczestnicy Targów zapoznali się zarówno z ofertą edukacyjną Uczelni jak i z ofertami pracy, praktyk i staży w firmach i instytucjach, które zaprezentowały się w formie stoisk. Pracodawcy zadeklarowali blisko 800 ofert pracy. W targach wzięło udział blisko 450 osób. Wśród uczestników byli uczniowie szkół ponadgimnazjalnych, studenci, absolwenci oraz osoby bezrobotne poszukujące pracy. W czasie targów odbyły się prelekcje tj.:„Budowanie wizerunku zawodowego za pomocą dokumentów aplikacyjnych” - Magdalena Woch – Knapik, „Zmiękcz myślenie. Doceń siłę kompetencji miękkich” – mgr Magdalena Pilawska, „Bezpieczeństwo w cyberprzestrzeni” – mgr Mateusz Zając.",
		"image": "images/5.jpg",
		"author": "Autor 3",
		"duration": "04.04.2018",
		"categories": ["#targi", " #praca"],
	},
]